package ncasa.expense.application.plan;
import java.time.*;import java.util.*;import ncasa.expense.application.*;import ncasa.expense.application.port.out.*;import ncasa.expense.domain.*;
public final class CreateExpensePlanUseCase {
 private final ExpensePlanRepository plans;private final HouseholdExpenseAccessPort access;private final ExpenseCategoryRepository categories;private final TransactionalOutboxPort outbox;private final Clock clock;
 public CreateExpensePlanUseCase(ExpensePlanRepository p,HouseholdExpenseAccessPort a,ExpenseCategoryRepository c,TransactionalOutboxPort o,Clock k){plans=p;access=a;categories=c;outbox=o;clock=k;}
 public ExpensePlanView execute(CreateExpensePlanCommand c){var household=new HouseholdRef(c.householdId());var context=access.getContext(household,c.actorAccountId());var zone=parseZone(c.zoneId());var today=LocalDate.now(clock.withZone(zone));if(c.startDate()==null||c.startDate().isBefore(today))throw new ExpenseRuleViolationException("Plan start date cannot be in the past");
  var payer=new MemberRef(c.payerMemberId());context.requireActive(payer);var total=new Money(c.amount(),c.currency());var split=split(c.split(),total,context);ExpenseCategoryId category=null;if(c.categoryId()!=null){category=new ExpenseCategoryId(c.categoryId());var found=categories.findByIdAndHousehold(category,household).orElseThrow(()->new CategoryNotFoundException("Expense category not found"));found.requireActive();}
  var schedule=new Schedule(Objects.requireNonNull(c.frequency()),c.startDate());var end=end(c,schedule);var plan=ExpensePlan.create(new ExpensePlanId(UUID.randomUUID()),household,context.actorMemberId(),new ExpenseTemplate(new ExpenseDescription(c.description()),total,payer,category,split),schedule,end,zone,c.reminderDaysBefore(),clock.instant());var saved=plans.save(plan);outbox.append(saved.id(),plan.pullEvents());return ExpensePlanView.from(saved);}
 private EndCondition end(CreateExpensePlanCommand c,Schedule s){if(s.frequency()==ExpensePlanFrequency.ONCE){if(c.endCondition()!=null||c.endDate()!=null||c.totalOccurrences()!=null)return invalid("One-time plan cannot contain an end condition");return EndCondition.afterOccurrences(1);}if("UNTIL_DATE".equals(c.endCondition())){if(c.endDate()==null||c.totalOccurrences()!=null)return invalid("UNTIL_DATE requires only endDate");return EndCondition.until(c.endDate());}if("AFTER_OCCURRENCES".equals(c.endCondition())){if(c.totalOccurrences()==null||c.endDate()!=null)return invalid("AFTER_OCCURRENCES requires only totalOccurrences");return EndCondition.afterOccurrences(c.totalOccurrences());}return invalid("End condition is required");}
 private <T>T invalid(String m){throw new ExpenseRuleViolationException(m);}private ZoneId parseZone(String value){try{return ZoneId.of(value);}catch(Exception e){throw new ExpenseRuleViolationException("Invalid IANA time zone");}}
 private TemplateSplit split(PlanSplitCommand command,Money total,ExpenseHouseholdContext context){if(command==null||command.type()==null)throw new ExpenseRuleViolationException("Split is required");if(command.type()==ExpenseSplitType.EQUAL){var members=safe(command.memberIds()).stream().map(MemberRef::new).toList();members.forEach(context::requireActive);return new EqualTemplateSplit(members);}if(command.type()==ExpenseSplitType.EXACT){var values=safe(command.allocations()).stream().map(a->{var member=new MemberRef(a.memberId());context.requireActive(member);return new ExpenseAllocation(member,new Money(a.amount(),total.currency()));}).toList();return new ExactTemplateSplit(values);}var values=safe(command.allocations()).stream().map(a->{var member=new MemberRef(a.memberId());context.requireActive(member);return new PercentageAllocation(member,Percentage.of(a.percentage()));}).toList();return new PercentageTemplateSplit(values);}
 private <T>List<T> safe(List<T> values){return values==null?List.of():values;}
}
