package ncasa.expense.infrastructure.persistence;
import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;import ncasa.expense.application.port.out.*;import ncasa.expense.domain.*;import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Repository;
@Repository public class JpaExpensePlanRepositoryAdapter implements ExpensePlanRepository{
 private final SpringDataExpensePlanRepository repository;public JpaExpensePlanRepositoryAdapter(SpringDataExpensePlanRepository r){repository=r;}
 public ExpensePlan save(ExpensePlan p){return domain(repository.saveAndFlush(entity(p)));}
 public Optional<ExpensePlan> findByIdAndHousehold(ExpensePlanId id,HouseholdRef h){return repository.findByIdAndHouseholdId(id.value(),h.value()).map(this::domain);}
 public ExpensePlanPageSlice findPage(HouseholdRef h,ExpensePlanStatus status,MemberRef payer,MemberRef participant,ExpensePlanFrequency frequency,LocalDate from,LocalDate to,int page,int size){var ids=repository.pageIds(h.value(),status==null?null:status.name(),payer==null?null:payer.value(),participant==null?null:participant.value(),frequency==null?null:frequency.name(),from,to,PageRequest.of(page,size));var map=repository.findByIdIn(ids.getContent()).stream().collect(Collectors.toMap(e->e.id,Function.identity()));return new ExpensePlanPageSlice(ids.getContent().stream().map(map::get).map(this::domain).toList(),ids.getTotalElements());}
 public List<ExpensePlan> findActiveForForecast(HouseholdRef h){var ids=repository.activeIds(h.value());return repository.findByIdIn(ids).stream().map(this::domain).toList();}
 public List<ExpensePlanId> findDueIds(Instant due,int limit){return repository.dueIds(due,limit).stream().map(ExpensePlanId::new).toList();}public Optional<ExpensePlan> findByIdForUpdate(ExpensePlanId id){return repository.findForUpdate(id.value()).map(this::domain);}public List<ExpensePlanId> findReminderDueIds(Instant due,int limit){return repository.reminderDueIds(due,limit).stream().map(ExpensePlanId::new).toList();}
 private JpaExpensePlanEntity entity(ExpensePlan p){var e=new JpaExpensePlanEntity();e.id=p.id().value();e.householdId=p.householdId().value();e.createdByMemberId=p.createdByMemberId().value();e.description=p.template().description().value();e.amount=p.template().total().amount();e.currency=p.template().total().currency();e.payerMemberId=p.template().payerMemberId().value();e.categoryId=p.template().categoryId()==null?null:p.template().categoryId().value();e.splitType=p.template().split().type().name();e.frequency=p.schedule().frequency().name();e.startDate=p.schedule().startDate();e.zoneId=p.zoneId().getId();e.endType=p.endCondition().type();e.endDate=p.endCondition().endDate();e.totalOccurrences=p.endCondition().occurrenceLimit();e.reminderDaysBefore=p.reminderDaysBefore();e.scheduleCursor=p.scheduleCursor();e.materializedOccurrences=p.materializedOccurrences();e.nextOccurrence=p.nextOccurrence();e.nextOccurrenceDueAt=p.nextOccurrenceDueAt();e.nextReminderAt=p.nextReminderAt();e.remindedOccurrenceKey=p.remindedOccurrenceKey();e.status=p.status().name();e.pauseReason=p.pauseReason();e.cancellationReason=p.cancellationReason();e.createdAt=p.createdAt();e.updatedAt=p.updatedAt();e.pausedAt=p.pausedAt();e.cancelledAt=p.cancelledAt();e.completedAt=p.completedAt();e.version=p.version();
  if(p.template().split() instanceof EqualTemplateSplit s)s.participants().forEach(m->e.add(allocation(p.id(),m,null,null)));else if(p.template().split() instanceof ExactTemplateSplit s)s.allocations().forEach(a->e.add(allocation(p.id(),a.memberId(),a.amount().amount(),null)));else if(p.template().split() instanceof PercentageTemplateSplit s)s.percentages().forEach(a->e.add(allocation(p.id(),a.memberId(),null,a.percentage().value())));return e;}
 private JpaExpensePlanAllocationEntity allocation(ExpensePlanId id,MemberRef member,java.math.BigDecimal amount,java.math.BigDecimal percentage){return new JpaExpensePlanAllocationEntity(UUID.nameUUIDFromBytes((id.value()+":"+member.value()).getBytes(StandardCharsets.UTF_8)),member.value(),amount,percentage);}
 private ExpensePlan domain(JpaExpensePlanEntity e){var money=new Money(e.amount,e.currency);TemplateSplit split;if("EQUAL".equals(e.splitType))split=new EqualTemplateSplit(e.allocations.stream().map(a->new MemberRef(a.memberId)).toList());else if("EXACT".equals(e.splitType))split=new ExactTemplateSplit(e.allocations.stream().map(a->new ExpenseAllocation(new MemberRef(a.memberId),new Money(a.amount,e.currency))).toList());else split=new PercentageTemplateSplit(e.allocations.stream().map(a->new PercentageAllocation(new MemberRef(a.memberId),Percentage.of(a.percentage))).toList());EndCondition end="UNTIL_DATE".equals(e.endType)?EndCondition.until(e.endDate):EndCondition.afterOccurrences(e.totalOccurrences);return ExpensePlan.rehydrate(new ExpensePlanId(e.id),new HouseholdRef(e.householdId),new MemberRef(e.createdByMemberId),new ExpenseTemplate(new ExpenseDescription(e.description),money,new MemberRef(e.payerMemberId),e.categoryId==null?null:new ExpenseCategoryId(e.categoryId),split),new Schedule(ExpensePlanFrequency.valueOf(e.frequency),e.startDate),end,ZoneId.of(e.zoneId),e.reminderDaysBefore,e.scheduleCursor,e.materializedOccurrences,e.nextOccurrence,ExpensePlanStatus.valueOf(e.status),e.remindedOccurrenceKey,e.pauseReason,e.cancellationReason,e.createdAt,e.updatedAt,e.pausedAt,e.cancelledAt,e.completedAt,e.version);}
}
