package ncasa.expense.infrastructure.persistence;
import jakarta.persistence.LockModeType;import java.time.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.repository.*;import org.springframework.data.repository.query.Param;
interface SpringDataExpensePlanRepository extends JpaRepository<JpaExpensePlanEntity,UUID>{
 @EntityGraph(attributePaths="allocations")Optional<JpaExpensePlanEntity> findByIdAndHouseholdId(UUID id,UUID householdId);
 @EntityGraph(attributePaths="allocations")List<JpaExpensePlanEntity> findByIdIn(Collection<UUID> ids);
 @Query(value="select p.id from JpaExpensePlanEntity p where p.householdId=:household and (:status is null or p.status=:status) and (:payer is null or p.payerMemberId=:payer) and (:participant is null or exists(select a.id from JpaExpensePlanAllocationEntity a where a.plan=p and a.memberId=:participant)) and (:frequency is null or p.frequency=:frequency) and (:fromDate is null or p.nextOccurrence>=:fromDate) and (:toDate is null or p.nextOccurrence<=:toDate) order by p.nextOccurrence,p.createdAt,p.id",countQuery="select count(p) from JpaExpensePlanEntity p where p.householdId=:household and (:status is null or p.status=:status) and (:payer is null or p.payerMemberId=:payer) and (:participant is null or exists(select a.id from JpaExpensePlanAllocationEntity a where a.plan=p and a.memberId=:participant)) and (:frequency is null or p.frequency=:frequency) and (:fromDate is null or p.nextOccurrence>=:fromDate) and (:toDate is null or p.nextOccurrence<=:toDate)")Page<UUID> pageIds(@Param("household")UUID household,@Param("status")String status,@Param("payer")UUID payer,@Param("participant")UUID participant,@Param("frequency")String frequency,@Param("fromDate")LocalDate from,@Param("toDate")LocalDate to,Pageable pageable);
 @Query("select p.id from JpaExpensePlanEntity p where p.householdId=:household and p.status='ACTIVE'")List<UUID> activeIds(@Param("household")UUID household);
 @Query(value="select id from expense_plans where status='ACTIVE' and next_occurrence_due_at<=:due order by next_occurrence_due_at,id limit :limit",nativeQuery=true)List<UUID> dueIds(@Param("due")Instant due,@Param("limit")int limit);
 @Query(value="select id from expense_plans where status='ACTIVE' and next_reminder_at is not null and next_reminder_at<=:due order by next_reminder_at,id limit :limit",nativeQuery=true)List<UUID> reminderDueIds(@Param("due")Instant due,@Param("limit")int limit);
 @Lock(LockModeType.PESSIMISTIC_WRITE)@EntityGraph(attributePaths="allocations")@Query("select p from JpaExpensePlanEntity p where p.id=:id")Optional<JpaExpensePlanEntity> findForUpdate(@Param("id")UUID id);
}
