package ncasa.expense.infrastructure.web;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import ncasa.expense.application.*;import ncasa.expense.application.forecast.*;import ncasa.expense.application.plan.*;import ncasa.expense.domain.*;import ncasa.identityaccess.infrastructure.security.IdentityUserDetails;import org.springframework.http.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/households/{householdId}/expense-plans") @Transactional public class ExpensePlanController{
 private final CreateExpensePlanUseCase create;private final GetExpensePlanUseCase get;private final ListExpensePlansUseCase list;private final ExpensePlanLifecycleUseCase lifecycle;private final ForecastExpensePlansUseCase forecast;
 public ExpensePlanController(CreateExpensePlanUseCase c,GetExpensePlanUseCase g,ListExpensePlansUseCase l,ExpensePlanLifecycleUseCase x,ForecastExpensePlansUseCase f){create=c;get=g;list=l;lifecycle=x;forecast=f;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED)PlanResponse create(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@Valid @RequestBody CreateRequest r){return PlanResponse.from(create.execute(r.command(user.id(),householdId)));}
 @GetMapping("/forecast")@Transactional(readOnly=true)ForecastResponse forecast(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to){return ForecastResponse.from(forecast.execute(user.id(),householdId,from,to));}
 @GetMapping("/{planId}")@Transactional(readOnly=true)PlanResponse get(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@PathVariable UUID planId){return PlanResponse.from(get.execute(user.id(),householdId,planId));}
 @GetMapping @Transactional(readOnly=true)PageResponse list(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@RequestParam(defaultValue="ACTIVE")ExpensePlanStatus status,@RequestParam(required=false)UUID payerMemberId,@RequestParam(required=false)UUID participantMemberId,@RequestParam(required=false)ExpensePlanFrequency frequency,@RequestParam(required=false)LocalDate nextOccurrenceFrom,@RequestParam(required=false)LocalDate nextOccurrenceTo,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){var value=list.execute(user.id(),householdId,status,payerMemberId,participantMemberId,frequency,nextOccurrenceFrom,nextOccurrenceTo,page,size);return new PageResponse(value.content().stream().map(PlanResponse::from).toList(),value.page(),value.size(),value.totalElements(),value.totalPages());}
 @PostMapping("/{planId}/pause")PlanResponse pause(@AuthenticationPrincipal IdentityUserDetails u,@PathVariable UUID householdId,@PathVariable UUID planId,@Valid @RequestBody PauseRequest r){return PlanResponse.from(lifecycle.execute(u.id(),householdId,planId,r.version(),ExpensePlanLifecycleUseCase.Action.PAUSE,r.reason()));}
 @PostMapping("/{planId}/reactivate")PlanResponse reactivate(@AuthenticationPrincipal IdentityUserDetails u,@PathVariable UUID householdId,@PathVariable UUID planId,@Valid @RequestBody VersionRequest r){return PlanResponse.from(lifecycle.execute(u.id(),householdId,planId,r.version(),ExpensePlanLifecycleUseCase.Action.REACTIVATE,null));}
 @PostMapping("/{planId}/cancel")PlanResponse cancel(@AuthenticationPrincipal IdentityUserDetails u,@PathVariable UUID householdId,@PathVariable UUID planId,@Valid @RequestBody CancelRequest r){return PlanResponse.from(lifecycle.execute(u.id(),householdId,planId,r.version(),ExpensePlanLifecycleUseCase.Action.CANCEL,r.reason()));}
 record CreateRequest(@NotNull @Valid TemplateRequest template,@NotNull @Valid ScheduleRequest schedule,@Valid EndRequest endCondition,@Min(0)@Max(30)int reminderDaysBefore){CreateExpensePlanCommand command(Long actor,UUID h){return new CreateExpensePlanCommand(actor,h,template.description(),template.amount(),template.currency(),template.payerMemberId(),template.categoryId(),template.split().command(),schedule.frequency(),schedule.startDate(),schedule.zoneId(),endCondition==null?null:endCondition.type(),endCondition==null?null:endCondition.endDate(),endCondition==null?null:endCondition.totalOccurrences(),reminderDaysBefore);}}
 record TemplateRequest(@NotBlank@Size(max=240)String description,@NotNull@DecimalMin(value="0",inclusive=false)BigDecimal amount,@NotBlank@Size(min=3,max=3)String currency,@NotNull UUID payerMemberId,UUID categoryId,@NotNull@Valid SplitRequest split){}
 record ScheduleRequest(@NotNull ExpensePlanFrequency frequency,@NotNull LocalDate startDate,@NotBlank String zoneId){}
 record EndRequest(@NotBlank String type,LocalDate endDate,@Min(1)Integer totalOccurrences){}
 record SplitRequest(@NotNull ExpenseSplitType type,List<UUID> memberIds,List<@Valid AllocationRequest> allocations){PlanSplitCommand command(){var values=allocations==null?List.<AllocationRequest>of():allocations;if(type==ExpenseSplitType.EQUAL){if(memberIds==null||memberIds.isEmpty()||!values.isEmpty())throw new IllegalArgumentException("EQUAL split requires only memberIds");}else if(type==ExpenseSplitType.EXACT){if(memberIds!=null&&!memberIds.isEmpty())throw new IllegalArgumentException("EXACT split cannot contain memberIds");values.forEach(a->{if(a.amount()==null||a.percentage()!=null)throw new IllegalArgumentException("EXACT allocations require only amount");});}else{if(memberIds!=null&&!memberIds.isEmpty())throw new IllegalArgumentException("PERCENTAGE split cannot contain memberIds");values.forEach(a->{if(a.percentage()==null||a.amount()!=null)throw new IllegalArgumentException("PERCENTAGE allocations require only percentage");});}return new PlanSplitCommand(type,memberIds,values.stream().map(a->new PlanSplitCommand.Allocation(a.memberId(),a.amount(),a.percentage())).toList());}}
 record AllocationRequest(@NotNull UUID memberId,@DecimalMin(value="0",inclusive=false)BigDecimal amount,@DecimalMin(value="0",inclusive=false)BigDecimal percentage){}
 record PauseRequest(@Min(0)long version,@Size(max=500)String reason){}record VersionRequest(@Min(0)long version){}record CancelRequest(@Min(0)long version,@NotBlank@Size(max=500)String reason){}
 record PageResponse(List<PlanResponse> content,int page,int size,long totalElements,int totalPages){}
 record PlanResponse(UUID id,UUID householdId,UUID createdByMemberId,TemplateResponse template,ExpensePlanFrequency frequency,LocalDate startDate,String zoneId,String endCondition,LocalDate endDate,Integer totalOccurrences,int reminderDaysBefore,int materializedOccurrences,LocalDate nextOccurrence,Instant nextOccurrenceDueAt,Instant nextReminderAt,ExpensePlanStatus status,String pauseReason,String cancellationReason,Instant createdAt,Instant updatedAt,Instant pausedAt,Instant cancelledAt,Instant completedAt,long version){static PlanResponse from(ExpensePlanView v){var t=v.template();return new PlanResponse(v.id(),v.householdId(),v.createdByMemberId(),new TemplateResponse(t.description(),t.amount().toPlainString(),t.currency(),t.payerMemberId(),t.categoryId(),t.splitType(),t.allocations().stream().map(a->new AllocationResponse(a.memberId(),a.amount()==null?null:a.amount().toPlainString(),a.percentage()==null?null:a.percentage().toPlainString())).toList()),v.frequency(),v.startDate(),v.zoneId(),v.endCondition(),v.endDate(),v.totalOccurrences(),v.reminderDaysBefore(),v.materializedOccurrences(),v.nextOccurrence(),v.nextOccurrenceDueAt(),v.nextReminderAt(),v.status(),v.pauseReason(),v.cancellationReason(),v.createdAt(),v.updatedAt(),v.pausedAt(),v.cancelledAt(),v.completedAt(),v.version());}}
 record TemplateResponse(String description,String amount,String currency,UUID payerMemberId,UUID categoryId,ExpenseSplitType splitType,List<AllocationResponse> allocations){}record AllocationResponse(UUID memberId,String amount,String percentage){}
 record ForecastResponse(UUID householdId,LocalDate from,LocalDate to,List<CurrencyResponse> currencies,List<OccurrenceResponse> occurrences){static ForecastResponse from(ExpensePlanForecast f){return new ForecastResponse(f.householdId(),f.from(),f.to(),f.currencies().stream().map(c->new CurrencyResponse(c.currency(),c.total().toPlainString())).toList(),f.occurrences().stream().map(o->new OccurrenceResponse(o.planId(),o.occurrenceKey(),o.occurrenceDate(),o.description(),o.amount().toPlainString(),o.currency(),o.payerMemberId(),o.categoryId(),o.allocations().stream().map(a->new OccurrenceAllocationResponse(a.memberId(),a.amount().toPlainString())).toList(),o.lastOccurrence())).toList());}}
 record CurrencyResponse(String currency,String total){}record OccurrenceResponse(UUID planId,String occurrenceKey,LocalDate occurrenceDate,String description,String amount,String currency,UUID payerMemberId,UUID categoryId,List<OccurrenceAllocationResponse> allocations,boolean lastOccurrence){}record OccurrenceAllocationResponse(UUID memberId,String amount){}
}
