package ncasa.expense.infrastructure.web;
import java.time.YearMonth;import java.util.*;import ncasa.expense.application.debt.*;import ncasa.expense.application.monthlybalance.*;import ncasa.identityaccess.infrastructure.security.IdentityUserDetails;import org.slf4j.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/households/{householdId}") @Transactional(readOnly=true)
public class FinancialSummaryController {
 private static final Logger LOG=LoggerFactory.getLogger(FinancialSummaryController.class);
 private final GetMonthlyFinancialSummaryUseCase monthly;private final GetDebtSummaryUseCase debt;public FinancialSummaryController(GetMonthlyFinancialSummaryUseCase monthly,GetDebtSummaryUseCase debt){this.monthly=monthly;this.debt=debt;}
 @GetMapping("/financial-summary/monthly") MonthlyResponse monthly(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@RequestParam String month){try{var response=MonthlyResponse.from(monthly.execute(user.id(),householdId,YearMonth.parse(month)));LOG.atInfo().addKeyValue("event.action","financial_summary_queried").addKeyValue("household.id",householdId).addKeyValue("summary.type","monthly").log("financial_summary_queried");return response;}catch(java.time.format.DateTimeParseException ex){throw new IllegalArgumentException("Month must use YYYY-MM format");}}
 @GetMapping("/debt-summary") DebtResponse debt(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId){var response=DebtResponse.from(debt.execute(user.id(),householdId));LOG.atInfo().addKeyValue("event.action","financial_summary_queried").addKeyValue("household.id",householdId).addKeyValue("summary.type","debt").log("financial_summary_queried");return response;}
 record MonthlyResponse(UUID householdId,String month,List<MonthlyCurrency> currencies){static MonthlyResponse from(MonthlyFinancialSummary s){return new MonthlyResponse(s.householdId(),s.month().toString(),s.currencies().stream().map(c->new MonthlyCurrency(c.currency(),decimal(c.totalExpenses()),c.members().stream().map(m->new MonthlyMember(m.memberId(),decimal(m.paid()),decimal(m.allocated()),decimal(m.net()))).toList())).toList());}}
 record MonthlyCurrency(String currency,String totalExpenses,List<MonthlyMember> members){} record MonthlyMember(UUID memberId,String paid,String allocated,String net){}
 record DebtResponse(UUID householdId,String asOf,List<DebtCurrency> currencies){static DebtResponse from(DebtSummary s){return new DebtResponse(s.householdId(),s.asOf().toString(),s.currencies().stream().map(c->new DebtCurrency(c.currency(),c.members().stream().map(m->new DebtMember(m.memberId(),decimal(m.paid()),decimal(m.allocated()),decimal(m.settledOut()),decimal(m.settledIn()),decimal(m.net()))).toList(),c.suggestedSettlements().stream().map(x->new Suggestion(x.fromMemberId(),x.toMemberId(),decimal(x.amount()))).toList())).toList());}}
 record DebtCurrency(String currency,List<DebtMember> members,List<Suggestion> suggestedSettlements){} record DebtMember(UUID memberId,String paid,String allocated,String settledOut,String settledIn,String net){} record Suggestion(UUID fromMemberId,UUID toMemberId,String amount){}
 private static String decimal(java.math.BigDecimal value){return value.toPlainString();}
}
