package ncasa.expense.infrastructure.web;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import ncasa.expense.application.*;import ncasa.expense.application.settlement.*;import ncasa.expense.domain.SettlementStatus;import ncasa.identityaccess.infrastructure.security.IdentityUserDetails;import org.slf4j.*;import org.springframework.http.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/households/{householdId}/settlements") @Transactional
public class SettlementController {
 private static final Logger LOG=LoggerFactory.getLogger(SettlementController.class);private final CreateSettlementUseCase create;private final GetSettlementUseCase get;private final ListSettlementsUseCase list;private final VoidSettlementUseCase voidSettlement;
 public SettlementController(CreateSettlementUseCase c,GetSettlementUseCase g,ListSettlementsUseCase l,VoidSettlementUseCase v){create=c;get=g;list=l;voidSettlement=v;}
 @PostMapping @Transactional(isolation=Isolation.SERIALIZABLE) ResponseEntity<Response> create(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@RequestHeader("Idempotency-Key") UUID key,@Valid @RequestBody CreateRequest request){var result=create.execute(new CreateSettlementCommand(user.id(),householdId,key,request.fromMemberId(),request.toMemberId(),request.amount(),request.currency(),request.settlementDate(),request.note()));LOG.atInfo().addKeyValue("event.action",result.replayed()?"settlement_replayed":"settlement_created").addKeyValue("settlement.id",result.settlement().id()).addKeyValue("household.id",householdId).log(result.replayed()?"settlement_replayed":"settlement_created");return ResponseEntity.status(result.replayed()?HttpStatus.OK:HttpStatus.CREATED).body(Response.from(result.settlement()));}
 @GetMapping("/{id}") @Transactional(readOnly=true) Response get(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@PathVariable UUID id){return Response.from(get.execute(user.id(),householdId,id));}
 @GetMapping @Transactional(readOnly=true) PageResponse list(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@RequestParam(required=false) LocalDate from,@RequestParam(required=false) LocalDate to,@RequestParam(required=false) SettlementStatus status,@RequestParam(required=false) UUID memberId,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return PageResponse.from(list.execute(new ListSettlementsQuery(user.id(),householdId,from,to,status,memberId,page,size)));}
 @PostMapping("/{id}/void") Response voidSettlement(@AuthenticationPrincipal IdentityUserDetails user,@PathVariable UUID householdId,@PathVariable UUID id,@Valid @RequestBody VoidRequest request){var result=voidSettlement.execute(user.id(),householdId,id,request.reason());LOG.atInfo().addKeyValue("event.action","settlement_voided").addKeyValue("settlement.id",id).addKeyValue("household.id",householdId).log("settlement_voided");return Response.from(result);}
 record CreateRequest(@NotNull UUID fromMemberId,@NotNull UUID toMemberId,@NotNull @DecimalMin(value="0",inclusive=false) BigDecimal amount,@NotBlank @Size(min=3,max=3) String currency,@NotNull LocalDate settlementDate,@Size(max=240) String note){} record VoidRequest(@NotBlank @Size(max=500) String reason){}
 record Response(UUID id,UUID householdId,UUID createdByMemberId,UUID fromMemberId,UUID toMemberId,String amount,String currency,LocalDate settlementDate,String note,SettlementStatus status,String voidReason,java.time.Instant createdAt,java.time.Instant updatedAt,java.time.Instant voidedAt,long version){static Response from(SettlementView s){return new Response(s.id(),s.householdId(),s.createdByMemberId(),s.fromMemberId(),s.toMemberId(),s.amount().toPlainString(),s.currency(),s.settlementDate(),s.note(),s.status(),s.voidReason(),s.createdAt(),s.updatedAt(),s.voidedAt(),s.version());}}
 record PageResponse(List<Response> items,int page,int size,long totalElements,int totalPages){static PageResponse from(SettlementPage p){return new PageResponse(p.items().stream().map(Response::from).toList(),p.page(),p.size(),p.totalElements(),p.totalPages());}}
}
