package ncasa.shoppinglist.infrastructure.persistence;
import java.time.Instant;import java.util.*;import ncasa.shoppinglist.application.port.out.ShoppingItemRepository;import ncasa.shoppinglist.domain.*;import org.springframework.stereotype.Repository;
@Repository public class JpaShoppingItemRepositoryAdapter implements ShoppingItemRepository{
 private final SpringDataShoppingItemRepository repository;public JpaShoppingItemRepositoryAdapter(SpringDataShoppingItemRepository r){repository=r;}
 public ShoppingItem save(ShoppingItem value){var row=repository.findById(value.id()).orElseGet(JpaShoppingItemEntity::new);row.id=value.id();row.listId=value.listId();row.name=value.name();row.quantity=value.quantity();row.unit=value.unit()==null?null:value.unit().name();row.customUnit=value.customUnit();row.note=value.note();row.responsibleMemberId=value.responsibleMemberId();row.addedByMemberId=value.addedByMemberId();row.purchasedByMemberId=value.purchasedByMemberId();row.status=value.status().name();row.position=value.position();row.createdAt=value.createdAt();row.updatedAt=value.updatedAt();row.purchasedAt=value.purchasedAt();return domain(repository.saveAndFlush(row));}
 public Optional<ShoppingItem> find(UUID id,UUID list){return repository.findByIdAndListId(id,list).map(this::domain);}public List<ShoppingItem> list(UUID list){return repository.findByListId(list).stream().map(this::domain).toList();}public long nextPendingPosition(UUID list){return repository.nextPendingPosition(list);}public void delete(ShoppingItem value){repository.deleteById(value.id());repository.flush();}public int deletePurchased(UUID list){int count=repository.deletePurchased(list);repository.flush();return count;}public int unassign(UUID household,UUID member,Instant now){int count=repository.unassign(household,member,now);repository.flush();return count;}
 public List<UUID> assignedListIds(UUID household,UUID member){return repository.assignedListIds(household,member);}
 private ShoppingItem domain(JpaShoppingItemEntity r){return ShoppingItem.rehydrate(r.id,r.listId,r.name,r.quantity,r.unit==null?null:ShoppingUnit.valueOf(r.unit),r.customUnit,r.note,r.responsibleMemberId,r.addedByMemberId,r.purchasedByMemberId,ShoppingItemStatus.valueOf(r.status),r.position,r.createdAt,r.updatedAt,r.purchasedAt,r.version);}
}
