package ncasa.shoppinglist.infrastructure.persistence;
import java.util.*;import ncasa.shoppinglist.application.port.out.ShoppingListRepository;import ncasa.shoppinglist.domain.*;import org.springframework.stereotype.Repository;
@Repository public class JpaShoppingListRepositoryAdapter implements ShoppingListRepository{
 private final SpringDataShoppingListRepository repository;public JpaShoppingListRepositoryAdapter(SpringDataShoppingListRepository r){repository=r;}
 public ShoppingList save(ShoppingList value){var row=repository.findById(value.id()).orElseGet(JpaShoppingListEntity::new);row.id=value.id();row.householdId=value.householdId();row.name=value.name();row.normalizedName=value.status()==ShoppingListStatus.ACTIVE?value.normalizedName():null;row.calendarSeriesId=value.calendarSeriesId();row.status=value.status().name();row.createdByMemberId=value.createdByMemberId();row.createdAt=value.createdAt();row.updatedAt=value.updatedAt();row.deletedAt=value.deletedAt();row.contentRevision=value.contentRevision();return domain(repository.saveAndFlush(row));}
 public Optional<ShoppingList> find(UUID id,UUID household){return repository.findByIdAndHouseholdId(id,household).map(this::domain);}public List<ShoppingList> list(UUID household,ShoppingListStatus status){return repository.findByHouseholdIdAndStatusOrderByUpdatedAtDescIdAsc(household,status.name()).stream().map(this::domain).toList();}
 public boolean existsActiveName(UUID household,String name,UUID excluded){return repository.existsActiveName(household,name,excluded);}public Optional<ShoppingList> findActiveByCalendarSeries(UUID series){return repository.findByCalendarSeriesIdAndStatus(series,ShoppingListStatus.ACTIVE.name()).map(this::domain);}public void delete(ShoppingList value){repository.deleteById(value.id());repository.flush();}
 public void touchContent(UUID listId,java.time.Instant now){repository.touchContent(listId,now);}
 public boolean advanceContentRevision(UUID listId,long expected,java.time.Instant now){return repository.advanceContentRevision(listId,expected,now)==1;}
 private ShoppingList domain(JpaShoppingListEntity r){String normalized=r.normalizedName==null?ShoppingListName.of(r.name).normalized():r.normalizedName;return ShoppingList.rehydrate(r.id,r.householdId,r.name,normalized,r.calendarSeriesId,ShoppingListStatus.valueOf(r.status),r.createdByMemberId,r.createdAt,r.updatedAt,r.deletedAt,r.version,r.contentRevision);}
}
