package ncasa.expense.application.occurrence;
import java.time.*;import java.util.*;import ncasa.expense.application.port.out.*;import ncasa.expense.domain.*;
public final class MaterializeDueExpensePlanUseCase{
 private final ExpensePlanRepository plans;private final ExpenseOccurrenceRepository expenses;private final ExpensePlanHouseholdStatePort household;private final TransactionalOutboxPort outbox;private final Clock clock;
 public MaterializeDueExpensePlanUseCase(ExpensePlanRepository p,ExpenseOccurrenceRepository e,ExpensePlanHouseholdStatePort h,TransactionalOutboxPort o,Clock c){plans=p;expenses=e;household=h;outbox=o;clock=c;}
 public void execute(ExpensePlanId id){var plan=plans.findByIdForUpdate(id).orElseThrow();if(plan.status()!=ExpensePlanStatus.ACTIVE||plan.nextOccurrenceDueAt().isAfter(clock.instant()))return;if(plan.reminderDaysBefore()==0&&plan.nextReminderAt()!=null&&!plan.nextReminderAt().isAfter(clock.instant()))plan.reminderPublished(clock.instant());var date=plan.nextOccurrence();String key=date.toString();if(expenses.exists(id,key)){plan.occurrenceMaterialized(date,clock.instant());save(plan);return;}var state=household.get(plan.householdId());if(!valid(plan,state)){plan.pauseForAttention("Template references an inactive member or category",clock.instant());save(plan);return;}var split=plan.template().split().materialize(plan.template().total());var expense=Expense.confirmedFromPlan(new ExpenseId(UUID.randomUUID()),plan.id(),plan.householdId(),plan.createdByMemberId(),plan.template().payerMemberId(),plan.template().total(),plan.template().description(),date,split,plan.template().categoryId(),clock.instant());expenses.save(expense);plan.occurrenceMaterialized(date,clock.instant());save(plan);}
 private boolean valid(ExpensePlan p,ExpensePlanHouseholdStatePort.State state){if(!state.activeMembers().contains(p.template().payerMemberId())||!state.activeMembers().containsAll(p.template().split().participants()))return false;return p.template().categoryId()==null||state.activeCategories().contains(p.template().categoryId());}
 private void save(ExpensePlan p){plans.save(p);outbox.append(p.id(),p.pullEvents());}
}
