package ncasa.notification.application;

import static org.junit.jupiter.api.Assertions.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import ncasa.notification.application.port.out.*;import ncasa.notification.domain.*;import org.junit.jupiter.api.Test;

class NotificationUseCasesTest{
    private static final UUID EVENT=UUID.randomUUID(),HOUSEHOLD=UUID.randomUUID(),PLAN=UUID.randomUUID(),CREATOR=UUID.randomUUID(),PAYER=UUID.randomUUID(),PARTICIPANT=UUID.randomUUID();
    private static final Instant NOW=Instant.parse("2026-09-04T10:00:00Z");
    @Test void createsOneReminderPerAffectedActiveAccountAndDeduplicatesRetries(){var repo=new Notifications();var plans=(ExpensePlanNotificationSourcePort)(h,p)->new ExpensePlanNotificationSourcePort.Context(PLAN,HOUSEHOLD,CREATOR,PAYER,Set.of(PAYER,PARTICIPANT),"Rent",null);var households=new Households(List.of(new HouseholdNotificationDirectoryPort.Member(PAYER,1L,true,false),new HouseholdNotificationDirectoryPort.Member(PARTICIPANT,2L,true,false)));var useCase=new ConsumeExpensePlanNotificationUseCase(repo,plans,households,new NotificationRecipientPolicy(),Clock.fixed(NOW,ZoneOffset.UTC));assertEquals(2,useCase.execute(command(NotificationKind.EXPENSE_PLAN_OCCURRENCE_APPROACHING)));assertEquals(0,useCase.execute(command(NotificationKind.EXPENSE_PLAN_OCCURRENCE_APPROACHING)));assertEquals(2,repo.values.size());}
    @Test void attentionTargetsCreatorAndAdministrator(){var repo=new Notifications();var admin=UUID.randomUUID();var plans=(ExpensePlanNotificationSourcePort)(h,p)->new ExpensePlanNotificationSourcePort.Context(PLAN,HOUSEHOLD,CREATOR,PAYER,Set.of(PARTICIPANT),"Rent","Inactive participant");var households=new Households(List.of(new HouseholdNotificationDirectoryPort.Member(CREATOR,1L,true,false),new HouseholdNotificationDirectoryPort.Member(admin,2L,true,true),new HouseholdNotificationDirectoryPort.Member(PARTICIPANT,3L,true,false)));var useCase=new ConsumeExpensePlanNotificationUseCase(repo,plans,households,new NotificationRecipientPolicy(),Clock.fixed(NOW,ZoneOffset.UTC));assertEquals(2,useCase.execute(command(NotificationKind.EXPENSE_PLAN_ATTENTION_REQUIRED)));assertTrue(repo.values.stream().allMatch(n->"Inactive participant".equals(n.attentionReason())));}
    @Test void archivedHouseholdCreatesNothing(){var repo=new Notifications();var plan=(ExpensePlanNotificationSourcePort)(h,p)->new ExpensePlanNotificationSourcePort.Context(PLAN,HOUSEHOLD,CREATOR,PAYER,Set.of(),"Rent",null);var directory=new Households(List.of()){public HouseholdNotificationDirectoryPort.Directory get(UUID id){return new HouseholdNotificationDirectoryPort.Directory(false,List.of());}};assertEquals(0,new ConsumeExpensePlanNotificationUseCase(repo,plan,directory,new NotificationRecipientPolicy(),Clock.fixed(NOW,ZoneOffset.UTC)).execute(command(NotificationKind.EXPENSE_PLAN_OCCURRENCE_APPROACHING)));}
    @Test void completedTaskNotifiesOtherActiveParticipantsOnly(){var repo=new Notifications();var inactive=UUID.randomUUID();var households=new Households(List.of(new HouseholdNotificationDirectoryPort.Member(PAYER,1L,true,false),new HouseholdNotificationDirectoryPort.Member(PARTICIPANT,2L,true,false),new HouseholdNotificationDirectoryPort.Member(inactive,3L,false,false)));var useCase=new CreateTaskCompletionNotificationsUseCase(repo,households,new NotificationRecipientPolicy(),Clock.fixed(NOW,ZoneOffset.UTC));var count=useCase.execute(new CreateTaskCompletionNotificationsCommand(PLAN,HOUSEHOLD,"Comprar",LocalDate.of(2026,9,12),Set.of(PAYER,PARTICIPANT,inactive),PAYER,NOW));assertEquals(1,count);assertEquals(new AccountRef(2L),repo.values.getFirst().recipient());assertEquals(NotificationKind.CALENDAR_TASK_COMPLETED,repo.values.getFirst().kind());}
    @Test void listAndReadOnlyUseAccessibleHouseholds(){var repo=new Notifications();var directory=new Households(List.of());var notification=Notification.create(new NotificationId(UUID.randomUUID()),new IntegrationEventId(EVENT),new AccountRef(1L),new HouseholdRef(HOUSEHOLD),new PlanRef(PLAN),NotificationKind.EXPENSE_PLAN_OCCURRENCE_APPROACHING,"Rent",new NotificationAmount(BigDecimal.TEN,"EUR"),LocalDate.of(2026,9,5),1,null,null,NOW,NOW);repo.values.add(notification);var page=new ListNotificationsUseCase(repo,directory).execute(1L,true,0,20);assertEquals(1,page.totalElements());var read=new MarkNotificationReadUseCase(repo,directory,Clock.fixed(NOW.plusSeconds(5),ZoneOffset.UTC)).execute(1L,notification.id().value());assertEquals(NOW.plusSeconds(5),read.readAt());assertEquals(0,new CountUnreadNotificationsUseCase(repo,directory).execute(1L));}
    private ConsumeExpensePlanNotificationCommand command(NotificationKind kind){return new ConsumeExpensePlanNotificationCommand(EVENT,kind,HOUSEHOLD,PLAN,new BigDecimal("20.00"),"EUR",LocalDate.of(2026,9,5),1,12,NOW);}
    static class Households implements HouseholdNotificationDirectoryPort{final List<Member>members;Households(List<Member>m){members=m;}public Directory get(UUID id){return new Directory(true,members);}public Set<UUID> activeHouseholdIds(Long account){return Set.of(HOUSEHOLD);}}
    static class Notifications implements NotificationRepository{final List<Notification>values=new ArrayList<>();public boolean exists(IntegrationEventId e,AccountRef a){return values.stream().anyMatch(n->n.eventId().equals(e)&&n.recipient().equals(a));}public void saveAll(List<Notification> n){values.addAll(n);}public Notification save(Notification n){return n;}public NotificationPageSlice findPage(AccountRef a,Set<HouseholdRef> h,boolean unread,int p,int s){var found=values.stream().filter(n->n.recipient().equals(a)&&h.contains(n.householdId())&&(!unread||n.isUnread())).toList();return new NotificationPageSlice(found,found.size());}public long countUnread(AccountRef a,Set<HouseholdRef> h){return values.stream().filter(n->n.recipient().equals(a)&&h.contains(n.householdId())&&n.isUnread()).count();}public Optional<Notification> findAccessible(NotificationId id,AccountRef a,Set<HouseholdRef> h){return values.stream().filter(n->n.id().equals(id)&&n.recipient().equals(a)&&h.contains(n.householdId())).findFirst();}public int markAllRead(AccountRef a,Set<HouseholdRef> h,Instant at){var found=values.stream().filter(n->n.recipient().equals(a)&&h.contains(n.householdId())&&n.isUnread()).toList();found.forEach(n->n.markRead(at));return found.size();}}
}
