package ncasa.expense.application;
import static org.junit.jupiter.api.Assertions.*;import java.time.*;import java.util.*;import ncasa.expense.application.forecast.*;import ncasa.expense.application.occurrence.*;import ncasa.expense.application.port.out.*;import ncasa.expense.domain.*;import org.junit.jupiter.api.Test;
class ExpensePlanUseCasesTest{
 private static final UUID HOUSEHOLD=UUID.fromString("00000000-0000-0000-0000-000000000010"),MEMBER=UUID.fromString("00000000-0000-0000-0000-000000000011");private static final Instant NOW=Instant.parse("2026-09-01T00:00:00Z");
 @Test void materializesDueOccurrenceAndCompletesOneTimePlan(){var plans=new Plans(plan(Schedule.once(LocalDate.of(2026,9,1)),EndCondition.afterOccurrences(1)));var occurrences=new Occurrences();var events=new Events();var useCase=new MaterializeDueExpensePlanUseCase(plans,occurrences,h->new ExpensePlanHouseholdStatePort.State(Set.of(new MemberRef(MEMBER)),Set.of()),events,Clock.fixed(NOW,ZoneOffset.UTC));useCase.execute(plans.plan.id());assertEquals(1,occurrences.values.size());assertEquals(ExpenseSource.PLAN,occurrences.values.getFirst().source());assertEquals(ExpensePlanStatus.COMPLETED,plans.plan.status());assertTrue(events.types.contains("ExpensePlanCompleted"));}
 @Test void forecastDoesNotPersistAndKeepsCurrenciesSeparate(){var eur=plan(Schedule.monthly(LocalDate.of(2026,9,1)),EndCondition.afterOccurrences(2));var usd=plan(Money.of("10","USD"),Schedule.once(LocalDate.of(2026,9,2)),EndCondition.afterOccurrences(1));var plans=new Plans(eur,usd);var access=(HouseholdExpenseAccessPort)(h,a)->new ExpenseHouseholdContext(h,new MemberRef(MEMBER),false,Set.of(new MemberRef(MEMBER)));var result=new ForecastExpensePlansUseCase(plans,access,Clock.fixed(NOW,ZoneOffset.UTC)).execute(1L,HOUSEHOLD,LocalDate.of(2026,9,1),LocalDate.of(2026,10,2));assertEquals(3,result.occurrences().size());assertEquals(List.of("EUR","USD"),result.currencies().stream().map(ExpensePlanForecast.CurrencyTotal::currency).toList());}
 private ExpensePlan plan(Schedule s,EndCondition e){return plan(Money.of("12","EUR"),s,e);}private ExpensePlan plan(Money money,Schedule s,EndCondition e){var m=new MemberRef(MEMBER);return ExpensePlan.create(new ExpensePlanId(UUID.randomUUID()),new HouseholdRef(HOUSEHOLD),m,new ExpenseTemplate(new ExpenseDescription("Plan"),money,m,null,new EqualTemplateSplit(List.of(m))),s,e,ZoneOffset.UTC,0,NOW.minusSeconds(1));}
 static final class Plans implements ExpensePlanRepository{ExpensePlan plan;final List<ExpensePlan> all;Plans(ExpensePlan...p){all=List.of(p);plan=p[0];p[0].pullEvents();if(p.length>1)p[1].pullEvents();}public ExpensePlan save(ExpensePlan p){plan=p;return p;}public Optional<ExpensePlan> findByIdAndHousehold(ExpensePlanId id,HouseholdRef h){return all.stream().filter(p->p.id().equals(id)&&p.householdId().equals(h)).findFirst();}public ExpensePlanPageSlice findPage(HouseholdRef h,ExpensePlanStatus s,MemberRef p,MemberRef x,ExpensePlanFrequency f,LocalDate a,LocalDate b,int page,int size){return new ExpensePlanPageSlice(all,all.size());}public List<ExpensePlan> findActiveForForecast(HouseholdRef h){return all;}public List<ExpensePlanId> findDueIds(Instant d,int l){return List.of(plan.id());}public Optional<ExpensePlan> findByIdForUpdate(ExpensePlanId id){return Optional.of(plan);}public List<ExpensePlanId> findReminderDueIds(Instant d,int l){return List.of();}}
 static final class Occurrences implements ExpenseOccurrenceRepository{final List<Expense>values=new ArrayList<>();public boolean exists(ExpensePlanId p,String k){return values.stream().anyMatch(e->p.equals(e.sourcePlanId())&&k.equals(e.occurrenceKey()));}public Expense save(Expense e){values.add(e);return e;}}
 static final class Events implements TransactionalOutboxPort{final List<String>types=new ArrayList<>();public void append(ExpensePlanId p,List<ExpensePlanEvent> e){types.addAll(e.stream().map(ExpensePlanEvent::type).toList());}}
}
